runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  mongoose_url: "mongodb+srv://developercircus:ssUQYZJxrf8V1FXy@cluster0.5tgih.mongodb.net/fyc?retryWrites=true&w=majority"
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto